import Link from 'next/link'
import React from 'react'
import Head from "next/head";

const Admin = () => {
  return (
    <>
    <Head>
           <title>SPEAK-UP : ADMIN</title>
           <meta
             name="description"
             content="Generated by developer for the who needs to be thier doubts and want to learn from the expert"
           />
           <link rel="icon" href="/neev.png" />
         </Head>
    <div className="flex items-center justify-center flex-col w-full h-full from-slate-600 bg-gradient-to-t ">
    <div className="bg-green-900 rounded p-2 px-5 absolute top-[5rem] z-10">
      <h1 className="text-white text-3xl uppercase">admin</h1>
    </div>
    <div className="border-4 border-white p-5 relative rounded bg-white/30 w-[30rem] shadow-3xl mb-[6.3rem]">
      <div className="flex items-center justify-center mt-9">
        <img src="/images/logo2.png " className="w-[12rem]" />
      </div>
      <form className="flex items-center justify-center flex-col ">
        <div className="relative">
          <div className="relative mb-6 ">
            <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
              <i className="fa-solid fa-envelope  text-green-900 text-3xl"></i>
            </div>
            <div className="absolute w-[2px] h-[36px] bg-green-700 top-[10px] bottom-[2rem] left-[52px]"></div>
            <input
              type="email"
              id="email"
              name="email"
              className="text-green-800  rounded-lg block w-[24rem] text-2xl pl-[4rem] p-3 dark:placeholder:text-green-900 bg-white dark:text-green-900 outline-none"
              placeholder="Your Email"
              autoComplete="off"
              required
            />
          </div>
        </div>
        <div className="relative">
          <div className="relative mb-5 ">
            <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
              <i className=" fa-solid fa-lock  text-green-900 text-3xl"></i>
            </div>
            <div className="absolute w-[2px] h-[36px] bg-green-700 top-[10px] bottom-[2rem] left-[52px]"></div>
            <input
              type="password"
              id="password"
              name="password"
              className="text-green-800  rounded-lg block w-[24rem] text-2xl pl-[4rem] p-3 dark:placeholder:text-green-900 bg-white dark:text-green-900 outline-none"
              placeholder="Your Password"
              autoComplete="off"
              required
            />
          </div>
          <div className="mb-10">
          <span className="text-xl">Don't have an account? <Link  className=" text-green-800 hover:text-green-600  " href={"/registered"}>Registration</Link></span>
          </div>
        </div>
        <input
          type="submit"
          value="login"
          className="bg-green-900 hover:bg-green-800 shadow-4xl  transition-all duration-300 text-white px-16 py-3 cursor-pointer rounded text-3xl "
        />
      </form>
    </div>
  </div>
  </>
  )
}

export default Admin