import Head from "next/head";
import React, { useEffect, useState } from "react";
import { ToastContainer, toast } from "react-toastify";


const deleteuser = () => {

  return (
    <>
      <Head>
        <title>SPEAK-UP : STUDENT </title>
        <meta
          name="description"
          content="Generated by developer for the who needs to be thier doubts and want to learn from the expert"
        />
        <link rel="icon" href="/neev.png" />
      </Head>
      <div className="flex items-center justify-center flex-col w-full h-full from-slate-600 bg-gradient-to-t">
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          pauseOnHover
          theme="light"
        />
        <div className="bg-green-900 rounded p-2 px-5 absolute top-[5rem] z-10">
          <h1 className="text-white text-3xl uppercase">DELETE PROFILE</h1>
        </div>
        <div className="border-4 border-white p-5 relative rounded bg-white/30 w-[30rem] shadow-3xl mb-[5.3rem]">
          <div className="flex items-center justify-center mt-9">
            <img src="/images/logo2.png " className="w-[12rem]" />
          </div>
          <form className="flex items-center justify-center flex-col ">
            <div className="relative">
              <div className="relative mb-6 ">
                <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                  <i className="fa-solid fa-envelope  text-green-900 text-3xl"></i>
                </div>
                <div className="absolute w-[2px] h-[36px] bg-green-700 top-[10px] bottom-[2rem] left-[52px]"></div>
                <input
                  type="email"
                  id="email"
                  name="email"
                  className="text-green-800 cursor-not-allowed rounded-lg block w-[24rem] text-2xl pl-[4rem] p-3 dark:placeholder:text-green-900 bg-white dark:text-green-900 outline-none"
                  placeholder="Your Email"
                  disabled
                  value={email}
                />
              </div>
            </div>
            <div className="relative">
              <div className="relative mb-5 ">
                <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                  <i className=" fa-solid fa-lock  text-green-900 text-3xl"></i>
                </div>
                <div className="absolute w-[2px] h-[36px] bg-green-700 top-[10px] bottom-[2rem] left-[52px]"></div>
                <input
                  type="password"
                  id="password"
                  name="password"
                  className="text-green-800  rounded-lg block w-[24rem] text-2xl pl-[4rem] p-3 dark:placeholder:text-green-900 bg-white dark:text-green-900 outline-none"
                  placeholder="Password"
                  autoComplete="off"
                  required
                />
              </div>
            </div>
            <div className="relative">
              <div className="relative mb-7 ">
                <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                  <i className=" fa-solid fa-lock  text-green-900 text-3xl"></i>
                </div>
                <div className="absolute w-[2px] h-[36px] bg-green-700 top-[10px] bottom-[2rem] left-[52px]"></div>
                <input
                  type="password"
                  id="cpassword"
                  name="cpassword"
                  className="text-green-800  rounded-lg block w-[24rem] text-2xl pl-[4rem] p-3 dark:placeholder:text-green-900 bg-white dark:text-green-900 outline-none"
                  placeholder="Confirm Password"
                  autoComplete="off"
                  required
              
                />
              </div>
            </div>
            <button
              type="submit"
              className="bg-green-900 w-[15rem] hover:bg-green-800 shadow-4xl  transition-all duration-300 text-white h-[3.8rem] cursor-pointer rounded text-3xl  flex items-center justify-center"
           >Delete
            </button>
          </form>
        </div>
      </div>
    </>
  );
};

export default deleteuser;
