import React, { useEffect } from "react";
import Hodnav from "./components/Hodnav";
import Hoddata from "./components/Hoddata";
import Head from "next/head";
import { useRouter } from 'next/router';

const Hodhome = () => {
  const router = useRouter();
  // useEffect(() => {
  //   if(!localStorage.getItem("hod-token")){
  //     router.push("/Hod")
  //   }
  // }, [])
  return (
    <>
    <Head>
           <title>SPEAK-UP : HOD HOME</title>
           <meta
             name="description"
             content="Generated by developer for the who needs to be thier doubts and want to learn from the expert"
           />
           <link rel="icon" href="/neev.png" />
         </Head>
    <div className="w-full h-[41.3rem] from-slate-600 bg-gradient-to-t">
      <div className="flex">
        <Hodnav />
        <Hoddata />
      </div>
    </div>
  </>
  );
};

export default Hodhome;
